# -----------------------------------------------------------------------------
# CI/CD Pipeline: Slack-Me Laravel CLI App
# Author: Dan McDermott
#
# Trigger:      On Git tag push matching pattern 'v*' (e.g., v1.0.0)
# Environment:  GitHub Environments are used to securely inject secrets.
# Purpose:
#   - Build and test the Laravel CLI app
#   - Inject secrets securely per environment (SLACK_SECRET, APP_KEY)
#   - Build final Docker image with no dev dependencies
#   - Push versioned and latest Docker tags to DockerHub
#
# Notes:
#   - APP_KEY and SLACK_SECRET are *never* baked into the Docker image.
#   - Laravel will receive both as runtime environment variables via docker run.
#   - GitHub Environment secrets are scoped per-tagged deploy (e.g., 'prod').
#   - This pipeline assumes tag-based deploys are production-only.
# -----------------------------------------------------------------------------

name: Dan McDermott CICD Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy to'
        required: true
        default: dev
        type: choice
        options:
          - prod
          - stg
          - dev
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      tag:
        required: false
        type: string        
    secrets:
      SLACK_SECRET:
        required: true
      APP_KEY:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true             
env:
  IMAGE_NAME: generalconsensus/rz-sl-me

jobs:
  # -----------------------------------------------------------------------------
  # JOB 1: Build & test the application using the test Docker stage
  # -----------------------------------------------------------------------------
  build-and-test:
    name: Build & Test Slack-Me App
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}  # Will work for `workflow_dispatch` only

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build test image (includes dev dependencies)
        run: docker build --file Dockerfile --target test -t slack-test .

      - name: Run Laravel unit tests in container
        env:
          SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
          APP_KEY: ${{ secrets.APP_KEY }}
        run: |
          docker run --rm \
            -e SLACK_SECRET="$SLACK_SECRET" \
            -e APP_KEY="$APP_KEY" \
            slack-test php artisan test --testdox
            
      - name: Echo event name
        run: echo "Event Name: ${{ github.event_name }}"

  # -----------------------------------------------------------------------------
  # JOB 2: Build the final production image (no dev deps) & push to DockerHub
  # -----------------------------------------------------------------------------
  docker:
    name: Build & Push Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest
    # Only run this job if a Git tag triggered the workflow
    if: github.event_name == 'workflow_call' && inputs.tag != ''

    # This deploys to the production environment
    environment:
      name: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image (production build, no dev dependencies)
        run: docker build --target release -t ${{ env.IMAGE_NAME }} .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          # Tag image with the Git tag and push to registry
          docker tag ${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          docker push ${{ env.IMAGE_NAME }}:${{ inputs.tag }}
          docker push ${{ env.IMAGE_NAME }}:latest

          # Also push as 'latest' for convenience
          docker push ${{ env.IMAGE_NAME }}:latest
